// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1855qJG2vzUmbGMCP6rLyrSyZavf2Y8',
    appId: '1:60224912980:web:afdd915aee8a078a77b7c1',
    messagingSenderId: '60224912980',
    projectId: 'aj-budgetr',
    authDomain: 'aj-budgetr.firebaseapp.com',
    storageBucket: 'aj-budgetr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuhwwi72qE6cIRWgvWFOP-4YKzzn6CmYs',
    appId: '1:60224912980:android:6a2d6e67fa4d154a77b7c1',
    messagingSenderId: '60224912980',
    projectId: 'aj-budgetr',
    storageBucket: 'aj-budgetr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDJ9Cr_4w-F4igxzhGLFY7-24F2cGjpDo',
    appId: '1:60224912980:ios:21e5b796d68a9d5f77b7c1',
    messagingSenderId: '60224912980',
    projectId: 'aj-budgetr',
    storageBucket: 'aj-budgetr.firebasestorage.app',
    iosBundleId: 'com.example.budget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDJ9Cr_4w-F4igxzhGLFY7-24F2cGjpDo',
    appId: '1:60224912980:ios:21e5b796d68a9d5f77b7c1',
    messagingSenderId: '60224912980',
    projectId: 'aj-budgetr',
    storageBucket: 'aj-budgetr.firebasestorage.app',
    iosBundleId: 'com.example.budget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA1855qJG2vzUmbGMCP6rLyrSyZavf2Y8',
    appId: '1:60224912980:web:41dbb3a68b418ccc77b7c1',
    messagingSenderId: '60224912980',
    projectId: 'aj-budgetr',
    authDomain: 'aj-budgetr.firebaseapp.com',
    storageBucket: 'aj-budgetr.firebasestorage.app',
  );
}
